### ISSUE TITLE
Jupyter Kernel dies repeatedly with basic commands including groupby

### ISSUE THREAD

**Issue by patrickbiltgen** [rapidsai/pygdf#283] opened 2018-10-13 02:05 UTC
When I attempt to execute the most basic example of the groupby statement 

import numpy as np
from pygdf import DataFrame
df = DataFrame()
nelem = 10**6  # A million item
df['key1'] = np.random.randint(0, 5, nelem)
df['key2'] = np.random.randint(0, 3, nelem)
df['val1'] = np.arange(1, 1 + nelem)
df['val2'] = np.random.random(nelem)

group_agg = df.groupby(by=['key1', 'key2']).mean()
group_agg.head(10).to_pandas()

The Jupyter Notebook kernel crashes every time. I am running on the Ubuntu Amazon EC2 machine learning base instance. Started with a clean install of Anaconda3, then ran this command to install pygdf:

conda install -c numba -c conda-forge -c gpuopenanalytics/label/dev -c defaults pygdf=0.1.0a3

Then loaded the notebook and started with the basic commands, and it crashes every time. Can't tell if there is another dependency? No errors are thrown. When I try to copy this to a .py file and run it, the code also crashes the kernel. Any suggestions please?

## Reporting a bug

- [x] I am using the latest version of PyGDF from conda or built from `master`.
- [ ] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [ ] I have included the following version information for:
      Arrow, CUDA, Numpy, Pandas, Python
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by kkraus14** [comment] 2018-10-14 11:15
@patrickbiltgen I believe this is related to issues with the build being uploaded to conda via TravisCI. We are working to address this in https://github.com/rapidsai/libgdf/pull/167 which should resolve this issue.

**Comment by patrickbiltgen** [comment] 2018-10-15 00:54
K^2 - thank you for the quick reply. This is a great project and I will stay tuned for the updates to Conda install. I will try to follow the instructions to build from source and see if that fixes the problem. Thank you for all your hard work on this.

**Comment by patrickbiltgen** [comment] 2018-10-15 01:12
I ran conda uninstall pygdf which said:

The following packages will be REMOVED:
    pygdf: 0.1.0a3-py36_263 gpuopenanalytics/label/dev

Then, using the command from https://github.com/rapidsai/pygdf I ran:
git clone https://github.com/gpuopenanalytics/pygdf.git
python setup.py install
from the anaconda3 directory.

Then, I started the Jupyter Notebook and clicked on the "Notebooks" folder and ran the example PYGDF Groupby Usage. In the first block where the dataframe is created, the command:
df['val2'] = np.random.random(nelem)

Throws the error: (very long but the end result is...)
GDFError: CUDA ERROR. cudaSuccess: no error

The df.head().to_pandas() command works fine, although it's missing the val2 column because I just deleted that line to make the previous code run.

Then when I attempt to run:

group_agg = df.groupby(by=['key1', 'key2']).mean()
group_agg.head(10).to_pandas()

The kernel dies. The actual error thrown in the command line from the Jupyter Notebook is:

 Notebook notebooks/Groupby Usage.ipynb is not trusted
[I 01:06:04.666 NotebookApp] Adapting to protocol v5.1 for kernel df17c0f1-984e-4157-a73e-d9cbff3f1b40
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: no kernel image is available for execution on the device

This is being run on the Amazon Deep Learning EC2 instance (Ubuntu 16.04 I believe). I updated Cuda 9.0 to 9.2. NVIDIA-SMI says the version is 396.54 and the driver version is 396.54. I'm running the g3s.xlarge instance, which NVIDIA-SMI says has one Tesla M60 GPU with 8GB of ram.

Any advice is greatly appreciated.

**Comment by dantegd** [comment] 2018-10-15 02:55
Hi @patrickbiltgen I believe the problem is the M60 GPU in the G3 instance. AFAIK libgdf (which contains the bulk of the computing kernels that pygdf uses) is currently supported/compiled for Pascal, Volta and Turing.

**Comment by dantegd** [comment] 2018-10-15 03:09
Additionally I believe this is related to an issue on the cmake gpu detection on libgdf: https://github.com/rapidsai/libgdf/issues/72 

@kkraus14 do you know the status on that issue? There seems to be a WIP PR about it.

**Comment by kkraus14** [comment] 2018-10-15 08:30
@patrickbiltgen You'd need to rebuild libgdf from source, not pygdf, as the kernel is likely dying due to a core dump or segfault from libgdf. 

> Hi @patrickbiltgen I believe the problem is the M60 GPU in the G3 instance. AFAIK libgdf (which contains the bulk of the computing kernels that pygdf uses) is currently supported/compiled for Pascal, Volta and Turing.

I believe this is correct, @mt-jones could you comment on this? I believe there are some build flags you can set to try to build for this architecture, but we are only supporting Pascal and newer architectures.

**Comment by patrickbiltgen** [comment] 2018-10-15 11:40
Thanks @kkraus14. I will try that. For reference, if I change the instance type from a g3 to a p3 (V100 GPU) then the groupby example provided on this site runs and does not crash the kernel as before when doing:

group_agg = df.groupby(by=['key1', 'key2']).mean()
group_agg.head(10).to_pandas()

I get an error in the next block:
group_agg = df.groupby(by=['key1', 'key2']).agg({'val1': ['count', 'mean'], 'val2': ['std']})

RuntimeError: ERROR: this aggregator has not been implemented yet

and then in the next one:
AttributeError: 'LibGdfGroupby' object has no attribute 'apply'

Which tends to comport with your recommendation to "rebuild libgdf from source." I will try that later today.

**Comment by jrhemstad** [comment] 2018-10-16 14:56
@patrickbiltgen It looks like this error is because we don't yet support standard deviation as a groupby aggregation yet.

**Comment by kkraus14** [comment] 2018-10-22 23:58
This should be fixed with the most recent conda builds, so I am closing but feel free to reopen if you experience similar issues.

**Closed by kkraus14** 2018-10-22 23:58 UTC
Labels: bug
